version: '3.8'

services:
  db:
    image: hackathon/postgres-migration:latest
    container_name: production-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

  app:
    image: postgres:latest
    container_name: production-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: org.postgresql.Driver

    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

volumes:
  postgres-db:
networks:
  backend:
    driver: bridge